sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  include:
    - php: '7.1'
      env: dependencies=lowest
    - php: '7.1'
      env: dependencies=highest
    - php: '7.2'
      env: dependencies=lowest
    - php: '7.2'
      env: dependencies=highest
    - php: nightly
      env: dependencies=lowest
    - php: nightly
      env: dependencies=highest

before_script:
  - travis_retry composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar.pubkey
  - chmod +x infection.phar

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text
  - phpdbg -qrr ./infection.phar --min-covered-msi=90 --threads=4 --show-mutations
